# Generated by Django 2.1.5 on 2021-06-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210607_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
