# Generated by Django 2.1.5 on 2021-06-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
