# Generated by Django 2.1.5 on 2021-06-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210607_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.CharField(default='javascript:void(0', max_length=500),
        ),
    ]
